version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


  flower:
    image: mher/flower:latest
    container_name: flower
    env_file:
      - .env
    environment:
      - FLOWER_BROKER=${CELERY_BROKER_URL}
      - FLOWER_PERSISTANT=true
    ports:
      - "5555:5555"
    depends_on:
      - redis


volumes:
  postgres_data:
